"""Menu lookup over data/menu.json.

The JSON is generated by scripts/scrape_menu.py from the Novikov website.
We expose three primitives the FAQ matcher needs:

- has_item(query)     -> Optional[Item]   "do you have X?"
- list_category(name) -> list[Item]       "what desserts do you have?"
- categories()        -> list[str]        useful for follow-up suggestions
"""

from __future__ import annotations

import json
import re
import unicodedata
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parents[2] / "data" / "menu.json"


@dataclass(frozen=True)
class MenuItem:
    slug: str
    name: str
    url: str
    categories: tuple[str, ...]
    price: str | None = None
    description: str | None = None
    dietary: tuple[str, ...] = ()
    allergens: tuple[str, ...] = ()


@dataclass(frozen=True)
class MenuIndex:
    items: tuple[MenuItem, ...]
    by_slug: dict[str, MenuItem]
    by_norm_name: dict[str, MenuItem]
    by_category_norm: dict[str, tuple[MenuItem, ...]]

    @property
    def category_names(self) -> list[str]:
        return sorted({c for it in self.items for c in it.categories})


# Common food terms callers may say in Russian/Spanish that we map to the
# English vocabulary used in the menu JSON. Keeps lookup script-agnostic.
_FOREIGN_TO_ENGLISH = {
    # Russian
    "лобстер": "lobster",
    "лобстера": "lobster",
    "томагавк": "tomahawk",
    "цезарь": "caesar",
    "спагетти": "spaghetti",
    "паста": "pasta",
    "пицца": "pizza",
    "пиццу": "pizza",
    "тирамису": "tiramisu",
    "стейк": "steak",
    "стейка": "steak",
    "креветки": "shrimp",
    "креветок": "shrimp",
    "говядина": "beef",
    "говядину": "beef",
    "курица": "chicken",
    "курицу": "chicken",
    "ризотто": "risotto",
    "рыба": "fish",
    "рыбу": "fish",
    "лосось": "salmon",
    "лосося": "salmon",
    "тунец": "tuna",
    "тунца": "tuna",
    "трюфель": "truffle",
    "трюфеля": "truffle",
    "икра": "caviar",
    "икру": "caviar",
    "устрицы": "oysters",
    "устриц": "oysters",
    "ягнёнок": "lamb",
    "ягненок": "lamb",
    "баранина": "lamb",
    "десерт": "dessert",
    "десерты": "desserts",
    "коктейль": "cocktail",
    "коктейли": "cocktails",
    "вино": "wine",
    "вина": "wine",
    # Spanish
    "langosta": "lobster",
    "carne": "meat",
    "pescado": "fish",
    "atún": "tuna",
    "atun": "tuna",
    "salmón": "salmon",
    "salmon": "salmon",
    "trufa": "truffle",
    "caviar": "caviar",
    "ostras": "oysters",
    "cordero": "lamb",
    "pollo": "chicken",
    "ternera": "beef",
    "camarones": "shrimp",
    "gamba": "shrimp",
    "gambas": "shrimp",
}

_TOKEN_SPLIT = re.compile(r"[^\w]+", re.UNICODE)
_STOPWORDS = frozenset(
    {
        "the", "a", "an", "and", "with", "of", "in", "for", "on",
        "y", "con", "de", "el", "la", "los", "las",
        "и", "с", "в", "на",
    }
)


def _normalize(text: str) -> str:
    text = unicodedata.normalize("NFKD", text or "")
    # Drop combining marks but keep base letters from any script.
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    return text.lower().strip()


def _translate_foreign(text: str) -> str:
    lower = text.lower()
    for foreign, english in _FOREIGN_TO_ENGLISH.items():
        if foreign in lower:
            lower = lower.replace(foreign, english)
    return lower


def _tokens(text: str) -> set[str]:
    norm = _normalize(_translate_foreign(text))
    # Drop any remaining non-ASCII tokens (script-mismatch with the
    # English-only menu index would just add noise).
    parts: list[str] = []
    for p in _TOKEN_SPLIT.split(norm):
        if not p or p in _STOPWORDS or len(p) <= 1:
            continue
        if any(ord(ch) > 127 for ch in p):
            continue
        parts.append(p)
    return set(parts)


_DIETARY_TAG_PATTERNS = (
    ("vegan", r"\bvegan\b"),
    ("vegetarian", r"\bvegetarian\b"),
    ("gluten_free", r"\bgluten[\s-]?free\b"),
    ("halal", r"\bhalal\b"),
)
# Allergen detection by name token. Conservative — used to flag dishes a
# caller with a stated allergy MUST avoid; the kitchen still confirms.
_ALLERGEN_TOKENS: dict[str, tuple[str, ...]] = {
    "nuts": (
        "pistachio", "almond", "almonds", "walnut", "walnuts",
        "hazelnut", "hazelnuts", "peanut", "peanuts", "cashew",
        "cashews", "pecan", "pecans", "praline", "macadamia",
    ),
    "shellfish": (
        "lobster", "shrimp", "shrimps", "oyster", "oysters",
        "crab", "crabs", "prawn", "prawns", "scallop", "scallops",
        "mussel", "mussels", "calamari", "octopus", "langoustine",
    ),
    "dairy": (
        "cheese", "cream", "butter", "parmesan", "ricotta",
        "mozzarella", "burrata", "yogurt", "milk", "tiramisu",
    ),
    "gluten": (
        "pasta", "pizza", "bread", "gnocchi", "spaghetti", "linguini",
        "tagliatelle", "tonnarelli", "ravioli", "tarte", "cake",
        "bruschetta", "tartlet", "milanese", "parmigiana",
    ),
    "fish": (
        "tuna", "salmon", "branzino", "seabass", "sea bass",
        "cod", "swordfish", "anchovy", "anchovies", "sardine",
        "sardines", "trout", "halibut",
    ),
    "egg": (
        "egg", "eggs", "carbonara", "tiramisu",
    ),
}


def _extract_dietary(description: str | None) -> tuple[str, ...]:
    if not description:
        return ()
    lower = description.lower()
    return tuple(tag for tag, pat in _DIETARY_TAG_PATTERNS if re.search(pat, lower))


def _extract_allergens(name: str) -> tuple[str, ...]:
    lower = name.lower()
    found: list[str] = []
    for allergen, tokens in _ALLERGEN_TOKENS.items():
        if any(re.search(rf"\b{re.escape(tok)}\b", lower) for tok in tokens):
            found.append(allergen)
    return tuple(found)


@lru_cache(maxsize=1)
def load_index(path: Path | None = None) -> MenuIndex:
    target = path or DATA_PATH
    if not target.exists():
        return MenuIndex(items=(), by_slug={}, by_norm_name={}, by_category_norm={})
    raw = json.loads(target.read_text())
    items: list[MenuItem] = []
    for entry in raw.get("items", []):
        name = entry.get("name", "")
        description = entry.get("description") or None
        items.append(
            MenuItem(
                slug=entry.get("slug", ""),
                name=name,
                url=entry.get("url", ""),
                categories=tuple(entry.get("categories", []) or ()),
                price=entry.get("price") or None,
                description=description,
                dietary=_extract_dietary(description),
                allergens=_extract_allergens(name),
            )
        )
    by_slug = {it.slug: it for it in items}
    by_norm_name = {_normalize(it.name): it for it in items}
    by_cat: dict[str, list[MenuItem]] = {}
    for it in items:
        for c in it.categories:
            by_cat.setdefault(_normalize(c), []).append(it)
    return MenuIndex(
        items=tuple(items),
        by_slug=by_slug,
        by_norm_name=by_norm_name,
        by_category_norm={k: tuple(v) for k, v in by_cat.items()},
    )


# Tokens that are too generic to drive a menu match on their own — they
# are filler for the booking flow, not specific dishes. A single-token
# overlap on these (e.g. caller says "table for 30 pm" matching dish
# "Bistecca 30oz" via "30") is meaningless.
_GENERIC_FILLER_TOKENS = frozenset({
    "can", "get", "have", "want", "need", "would", "like", "table",
    "tonight", "tomorrow", "today", "time", "pm", "am",
    "and", "or", "the", "for", "with",
})


def has_item(query: str, *, min_token_overlap: int = 1) -> MenuItem | None:
    """Return the best-matching item or None.

    Strategy:
    1. Exact normalized-name hit.
    2. All query tokens present in some item name.
    3. >= min_token_overlap meaningful (non-numeric, non-filler) tokens
       overlap; tiebreak by category priority + shorter name.
    """
    idx = load_index()
    if not idx.items:
        return None
    norm_query = _normalize(query)
    if not norm_query:
        return None
    if norm_query in idx.by_norm_name:
        return idx.by_norm_name[norm_query]

    q_tokens = _tokens(query)
    if not q_tokens:
        return None

    best: tuple[int, int, int, str, MenuItem] | None = None
    for it in idx.items:
        i_tokens = _tokens(it.name)
        common = q_tokens & i_tokens
        # Require at least one meaningful overlap — bare digit / filler
        # token overlap doesn't count as 'the caller asked about this dish'.
        meaningful = {
            tok for tok in common
            if not tok.isdigit() and tok not in _GENERIC_FILLER_TOKENS
        }
        if not meaningful:
            continue
        full = q_tokens.issubset(i_tokens)
        score = len(meaningful) * 10 + (5 if full else 0)
        if score < min_token_overlap * 10:
            continue
        cat_priority = 1 if "A La Carte" in it.categories else 0
        candidate = (score, cat_priority, -len(it.name), it.slug, it)
        if best is None or candidate[:4] > best[:4]:
            best = candidate
    return best[4] if best else None


def list_category(category_query: str, *, limit: int = 8) -> list[MenuItem]:
    idx = load_index()
    norm = _normalize(category_query)
    if not norm:
        return []
    if norm in idx.by_category_norm:
        return list(idx.by_category_norm[norm])[:limit]
    for cat_norm, dishes in idx.by_category_norm.items():
        if norm in cat_norm or cat_norm in norm:
            return list(dishes)[:limit]
    return []


def categories() -> list[str]:
    return load_index().category_names


def list_dietary(tag: str, *, limit: int = 8) -> list[MenuItem]:
    """Return menu items matching a dietary tag (vegan/vegetarian/gluten_free/halal)."""
    norm = tag.lower().replace("-", "_").replace(" ", "_")
    if norm.startswith("gluten"):
        norm = "gluten_free"
    if norm not in {"vegan", "vegetarian", "gluten_free", "halal"}:
        return []
    idx = load_index()
    return [it for it in idx.items if norm in it.dietary][:limit]


def safe_for_allergen(allergen: str, *, limit: int = 8) -> list[MenuItem]:
    """Return dishes whose names do NOT contain the given allergen marker.

    Filters out wines, since they're not dishes. Heuristic only — kitchen
    must still confirm. The caller should always be told to confirm with
    the host team.
    """
    norm = allergen.lower().strip()
    aliases = {
        "nut": "nuts",
        "nuts": "nuts",
        "peanut": "nuts",
        "peanuts": "nuts",
        "tree nut": "nuts",
        "tree nuts": "nuts",
        "shellfish": "shellfish",
        "seafood": "shellfish",
        "lactose": "dairy",
        "dairy": "dairy",
        "milk": "dairy",
        "cheese": "dairy",
        "gluten": "gluten",
        "wheat": "gluten",
        "fish": "fish",
        "egg": "egg",
        "eggs": "egg",
    }
    canonical = aliases.get(norm)
    if canonical not in _ALLERGEN_TOKENS:
        return []
    idx = load_index()
    food_categories = {
        "Appetizers & Charcuterie", "Salads", "Pasta, Risotto & Soup",
        "Meat", "Fish & Seafood", "Sides", "MEDITERRANEAN MEZE",
        "Carpaccio & Tartare", "First Course", "Second Course",
        "A La Carte", "Chef's Special", "Chef's Seasonal Special",
    }
    out: list[MenuItem] = []
    for it in idx.items:
        if canonical in it.allergens:
            continue
        if not any(c in food_categories for c in it.categories):
            continue
        out.append(it)
    return out[:limit]


def allergens_for(slug: str) -> tuple[str, ...]:
    item = load_index().by_slug.get(slug)
    return item.allergens if item else ()
